baseURL = 'sochriscoded.github.io'
languageCode = 'en-us'
title = 'Christopher Smith'
theme = 'chriscoded'

pagination.pagerSize = 100

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "series"
name = "Learn"
url = "/series/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"


[params.profileMode]
enabled = true
title = "Chris Coded"
subtitle = "Southern Hospitality Flavored Computer Science"
imageUrl = "logo.png"
imageTitle = "Chris Coded"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Blog"
  url = "/blog"

  [[params.profileMode.buttons]]
  name = "Learn"
  url = "/series/"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://www.github.com/sochriscoded"

[[params.socialIcons]]
name = "twitter"
url = "www.x.com/sochriscoded"

[[params.socialIcons]]
name = "youtube"
url = "www.youtube.com/@sochriscoded"
