baseURL = 'sochriscoded.github.io'
languageCode = 'en-us'
title = 'Chris Coded'
theme = "PaperMod"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "exercises"
name = "Exercises"
url = "/exercises/"
weight = 20

[[menu.main]]
identifier = "guides"
name = "Guides"
url = "/guides/"
weight = 30

[[menu.main]]
identifier = "tutorials"
name = "Tutorials"
url = "/tutorials/"
weight = 40

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 50

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"